"""blog table

Revision ID: 55291716bf8c
Revises: 
Create Date: 2020-04-05 03:58:16.268170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55291716bf8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.String(length=140), nullable=True))
    op.add_column('post', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_post_date_posted'), 'post', ['date_posted'], unique=False)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_column('post', 'timestamp')
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_post_date_posted'), table_name='post')
    op.drop_column('post', 'title')
    op.drop_column('post', 'date_posted')
    op.drop_column('post', 'content')
    # ### end Alembic commands ###
